estilização do header
carlospolli/carlospolli.github.io pull request #4
Opened 2021-08-13 16:22 UTC by julianasf-91

Fiz a estilização do Header conforme o layout do Figma, os estilos estão em common.css, pois o estilo do header aparecerá em todas as páginas.

2021-08-13 17:14 UTC, carlospolli requested changes
Ju, tem só um errinho fácil de arrumar ali, até deixei a sugestão. 
Mas tem um problema no html, tem um SVG Gigantesco salvo como texto no html, ta sujando muito que é o da foto, substitui o svg por uma imagem mesmo, pra ficar melhor!
Mas é isso ficou bom, parabéns! 
Vamos pensar em substituir todos os svgs dps p imagem.

2021-08-13 17:14 UTC, carlospolli commented on css/common.css
> +.header_side {
no header side, como ta em altura fixa em 900px, ele não completa em monitores maiores.
![image](https://user-images.githubusercontent.com/41194983/129394822-d66608aa-7f13-4989-a62a-c4144403d652.png)

Sugestão: Deixar height como 100%

2021-08-13 18:58 UTC, julianasf-91 commented on css/common.css
> +.header_side {
Alteração realizada.

2021-08-16 10:52 UTC, carlospolli commented
LGTM!

2021-08-16 10:52 UTC, merged